name: Daily Commit

on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6:00 AM UTC

jobs:
  update-number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the script
        run: python update_number.py
